                                                                                                                                                                                                                                                                                                                                    package com.example.utanglog.screens.adddebt

                                                                                                                                                                                                                                                                                                                                    import android.app.Activity
                                                                                                                                                                                                                                                                                                                                    import android.app.AlertDialog
                                                                                                                                                                                                                                                                                                                                    import android.app.DatePickerDialog
                                                                                                                                                                                                                                                                                                                                    import android.content.Intent
                                                                                                                                                                                                                                                                                                                                    import android.graphics.Bitmap
                                                                                                                                                                                                                                                                                                                                    import android.graphics.BitmapFactory
                                                                                                                                                                                                                                                                                                                                    import android.graphics.Canvas
                                                                                                                                                                                                                                                                                                                                    import android.graphics.Paint
                                                                                                                                                                                                                                                                                                                                    import android.graphics.PorterDuff
                                                                                                                                                                                                                                                                                                                                    import android.graphics.PorterDuffXfermode
                                                                                                                                                                                                                                                                                                                                    import android.graphics.Rect
                                                                                                                                                                                                                                                                                                                                    import android.net.Uri
                                                                                                                                                                                                                                                                                                                                    import android.os.Bundle
                                                                                                                                                                                                                                                                                                                                    import android.provider.MediaStore
                                                                                                                                                                                                                                                                                                                                    import android.widget.ArrayAdapter
                                                                                                                                                                                                                                                                                                                                    import android.widget.Button
                                                                                                                                                                                                                                                                                                                                    import android.widget.EditText
                                                                                                                                                                                                                                                                                                                                    import android.widget.ImageView
                                                                                                                                                                                                                                                                                                                                    import android.widget.Spinner
                                                                                                                                                                                                                                                                                                                                    import android.widget.Toast
                                                                                                                                                                                                                                                                                                                                    import com.example.utanglog.R
                                                                                                                                                                                                                                                                                                                                    import com.example.utanglog.screens.displaydebt.DisplayDebtActivity
                                                                                                                                                                                                                                                                                                                                    import com.example.utanglog.screens.profile.ProfileActivity
                                                                                                                                                                                                                                                                                                                                    import com.example.utanglog.utils.getEditTextValue
                                                                                                                                                                                                                                                                                                                                    import com.google.android.material.bottomnavigation.BottomNavigationView
                                                                                                                                                                                                                                                                                                                                    import java.io.File
                                                                                                                                                                                                                                                                                                                                    import java.io.FileOutputStream
                                                                                                                                                                                                                                                                                                                                    import java.util.Calendar
                                                                                                                                                                                                                                                                                                                                    import kotlin.math.min

                                                                                                                                                                                                                                                                                                                                    class AddDebtActivity : Activity(), AddDebtContract.View {

                                                                                                                                                                                                                                                                                                                                        private lateinit var presenter: AddDebtPresenter
                                                                                                                                                                                                                                                                                                                                        private lateinit var datePickerDialog: DatePickerDialog
                                                                                                                                                                                                                                                                                                                                        private lateinit var statusSpinner: Spinner
                                                                                                                                                                                                                                                                                                                                        private lateinit var imageviewDebtorAvatar: ImageView
                                                                                                                                                                                                                                                                                                                                        private var selectedImagePath: String = ""  // Store actual image path
                                                                                                                                                                                                                                                                                                                                        private val PICK_IMAGE_REQUEST = 1001

                                                                                                                                                                                                                                                                                                                                        override fun onCreate(savedInstanceState: Bundle?) {
                                                                                                                                                                                                                                                                                                                                            super.onCreate(savedInstanceState)
                                                                                                                                                                                                                                                                                                                                            setContentView(R.layout.activity_add_debt)

                                                                                                                                                                                                                                                                                                                                            presenter = AddDebtPresenter(this, AddDebtModel())

                                                                                                                                                                                                                                                                                                                                            setupStatusSpinner()
                                                                                                                                                                                                                                                                                                                                            setupDatePicker()
                                                                                                                                                                                                                                                                                                                                            setupBottomNavigation()

                                                                                                                                                                                                                                                                                                                                            imageviewDebtorAvatar = findViewById(R.id.imageviewDebtorAvatar)

                                                                                                                                                                                                                                                                                                                                            findViewById<Button>(R.id.btn_submit).setOnClickListener {
                                                                                                                                                                                                                                                                                                                                                presenter.onSubmitClick()
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            imageviewDebtorAvatar.setOnClickListener {
                                                                                                                                                                                                                                                                                                                                                showImagePickerDialog()
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun showImagePickerDialog() {
                                                                                                                                                                                                                                                                                                                                            val options = arrayOf("Choose from Gallery", "Cancel")
                                                                                                                                                                                                                                                                                                                                            AlertDialog.Builder(this)
                                                                                                                                                                                                                                                                                                                                                .setTitle("Select Debtor Photo")
                                                                                                                                                                                                                                                                                                                                                .setItems(options) { _, which ->
                                                                                                                                                                                                                                                                                                                                                    when (which) {
                                                                                                                                                                                                                                                                                                                                                        0 -> openGallery()
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                .show()
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun openGallery() {
                                                                                                                                                                                                                                                                                                                                            val intent = Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI)
                                                                                                                                                                                                                                                                                                                                            intent.type = "image/*"
                                                                                                                                                                                                                                                                                                                                            startActivityForResult(intent, PICK_IMAGE_REQUEST)
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
                                                                                                                                                                                                                                                                                                                                            super.onActivityResult(requestCode, resultCode, data)
                                                                                                                                                                                                                                                                                                                                            if (requestCode == PICK_IMAGE_REQUEST && resultCode == RESULT_OK) {
                                                                                                                                                                                                                                                                                                                                                val imageUri = data?.data
                                                                                                                                                                                                                                                                                                                                                if (imageUri != null) {
                                                                                                                                                                                                                                                                                                                                                    // Save the actual image and get the path
                                                                                                                                                                                                                                                                                                                                                    selectedImagePath = saveImageToStorage(imageUri)
                                                                                                                                                                                                                                                                                                                                                    loadImageIntoView(selectedImagePath)
                                                                                                                                                                                                                                                                                                                                                    Toast.makeText(this, "Photo selected", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun saveImageToStorage(imageUri: Uri): String {
                                                                                                                                                                                                                                                                                                                                            val inputStream = contentResolver.openInputStream(imageUri)
                                                                                                                                                                                                                                                                                                                                            val file = File(filesDir, "debtor_images")
                                                                                                                                                                                                                                                                                                                                            if (!file.exists()) {
                                                                                                                                                                                                                                                                                                                                                file.mkdirs()
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            val fileName = "debtor_${System.currentTimeMillis()}.jpg"
                                                                                                                                                                                                                                                                                                                                            val imageFile = File(file, fileName)
                                                                                                                                                                                                                                                                                                                                            val outputStream = FileOutputStream(imageFile)

                                                                                                                                                                                                                                                                                                                                            inputStream?.copyTo(outputStream)
                                                                                                                                                                                                                                                                                                                                            inputStream?.close()
                                                                                                                                                                                                                                                                                                                                            outputStream.close()

                                                                                                                                                                                                                                                                                                                                            return imageFile.absolutePath
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun loadImageIntoView(imagePath: String) {
                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                val originalBitmap = BitmapFactory.decodeFile(imagePath)
                                                                                                                                                                                                                                                                                                                                                if (originalBitmap != null) {
                                                                                                                                                                                                                                                                                                                                                    val circularBitmap = getCircularBitmap(originalBitmap)
                                                                                                                                                                                                                                                                                                                                                    imageviewDebtorAvatar.setImageBitmap(circularBitmap)
                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                    imageviewDebtorAvatar.setImageResource(R.drawable.ic_person_placeholder)
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            } catch (e: Exception) {
                                                                                                                                                                                                                                                                                                                                                imageviewDebtorAvatar.setImageResource(R.drawable.ic_person_placeholder)
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun getCircularBitmap(bitmap: Bitmap): Bitmap {
                                                                                                                                                                                                                                                                                                                                            val size = min(bitmap.width, bitmap.height)
                                                                                                                                                                                                                                                                                                                                            val output = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888)
                                                                                                                                                                                                                                                                                                                                            val canvas = Canvas(output)

                                                                                                                                                                                                                                                                                                                                            val paint = Paint()
                                                                                                                                                                                                                                                                                                                                            paint.isAntiAlias = true

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     val rect = Rect(0, 0, size, size)
                                                                                                                                                                                                                                                                                                                                            val srcRect = Rect(
                                                                                                                                                                                                                                                                                                                                                (bitmap.width - size) / 2,
                                                                                                                                                                                                                                                                                                                                                (bitmap.height - size) / 2,
                                                                                                                                                                                                                                                                                                                                                (bitmap.width + size) / 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (bitmap.height + size) / 2
                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                            canvas.drawCircle(size / 2f, size / 2f, size / 2f, paint)
                                                                                                                                                                                                                                                                                                                                            paint.xfermode = PorterDuffXfermode(PorterDuff.Mode.SRC_IN)
                                                                                                                                                                                                                                                                                                                                            canvas.drawBitmap(bitmap, srcRect, rect, paint)

                                                                                                                                                                                                                                                                                                                                            return output
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                     private fun setupBottomNavigation() {
                                                                                                                                                                                                                                                                                                                                            val bottomNav = findViewById<BottomNavigationView>(R.id.bottomNavigation)
                                                                                                                                                                                                                                                                                                                                            bottomNav.selectedItemId = R.id.nav_add
                                                                                                                                                                                                                                                                                                                                            bottomNav.setOnItemSelectedListener { item ->
                                                                                                                                                                                                                                                                                                                                                when (item.itemId) {
                                                                                                                                                                                                                                                                                                                                                    R.id.nav_home -> {
                                                                                                                                                                                                                                                                                                                                                        finish()
                                                                                                                                                                                                                                                                                                                                                        true
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    R.id.nav_add -> {
                                                                                                                                                                                                                                                                                                                                                        true
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    R.id.nav_profile -> {
                                                                                                                                                                                                                                                                                                                                                        startActivity(Intent(this, ProfileActivity::class.java))
                                                                                                                                                                                                                                                                                                                                                        finish()
                                                                                                                                                                                                                                                                                                                                                        true
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    else -> false
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun setupStatusSpinner() {
                                                                                                                                                                                                                                                                                                                                            statusSpinner = findViewById(R.id.spinnerStatus)
                                                                                                                                                                                                                                                                                                                                            val statusOptions = listOf("Pending", "Overdue", "Paid")
                                                                                                                                                                                                                                                                                                                                            val adapter = ArrayAdapter(this, android.R.layout.simple_spinner_item, statusOptions)
                                                                                                                                                                                                                                                                                                                                            adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
                                                                                                                                                                                                                                                                                                                                            statusSpinner.adapter = adapter
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        private fun setupDatePicker() {
                                                                                                                                                                                                                                                                                                                                            val today = Calendar.getInstance()
                                                                                                                                                                                                                                                                                                                                            datePickerDialog = DatePickerDialog(
                                                                                                                                                                                                                                                                                                                                                this,
                                                                                                                                                                                                                                                                                                                                                { _, year, month, dayOfMonth ->
                                                                                                                                                                                                                                                                                                                                                    val date = "$dayOfMonth/${month + 1}/$year"
                                                                                                                                                                                                                                                                                                                                                    findViewById<EditText>(R.id.edittextDueDate).setText(date)
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                today.get(Calendar.YEAR),
                                                                                                                                                                                                                                                                                                                                                today.get(Calendar.MONTH),
                                                                                                                                                                                                                                                                                                                                                today.get(Calendar.DAY_OF_MONTH)
                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                            findViewById<EditText>(R.id.edittextDueDate).setOnClickListener {
                                                                                                                                                                                                                                                                                                                                                datePickerDialog.show()
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        override fun getName(): String = getEditTextValue(R.id.edittextName)

                                                                                                                                                                                                                                                                                                                                        override fun getAmount(): Double {
                                                                                                                                                                                                                                                                                                                                            val amountStr = getEditTextValue(R.id.edittextAmount)
                                                                                                                                                                                                                                                                                                                                            return amountStr.toDoubleOrNull() ?: 0.0
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        override fun getStatus(): String = statusSpinner.selectedItem.toString()

                                                                                                                                                                                                                                                                                                                                        override fun getDueDate(): String = getEditTextValue(R.id.edittextDueDate)

                                                                                                                                                                                                                                                                                                                                        override fun getAddress(): String = getEditTextValue(R.id.edittextAddress)

                                                                                                                                                                                                                                                                                                                                        override fun getPhotoRes(): String = selectedImagePath  // Return path, not drawable

                                                                                                                                                                                                                                                                                                                                        override fun showSuccess(name: String, amount: Double) {
                                                                                                                                                                                                                                                                                                                                            Toast.makeText(this, "Added: $name - ₱$amount", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        override fun showError(message: String) {
                                                                                                                                                                                                                                                                                                                                            Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        override fun closeScreen(name: String, amount: Double, status: String, dueDate: String, address: String, photoPath: String) {
                                                                                                                                                                                                                                                                                                                                            val resultIntent = Intent().apply {
                                                                                                                                                                                                                                                                                                                                                putExtra("name", name)
                                                                                                                                                                                                                                                                                                                                                putExtra("amount", amount)
                                                                                                                                                                                                                                                                                                                                                putExtra("status", status)
                                                                                                                                                                                                                                                                                                                                                putExtra("dueDate", dueDate)
                                                                                                                                                                                                                                                                                                                                                putExtra("address", address)
                                                                                                                                                                                                                                                                                                                                                putExtra("photoPath", photoPath)  // Send path, not drawable
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            setResult(Activity.RESULT_OK, resultIntent)
                                                                                                                                                                                                                                                                                                                                            finish()
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    }